name: CI Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Visa meddelande
      run: echo \"Testkörning:ändring i CI-workflow fungerar\"
